export const homePage = {
  title: 'Diamantina cuida do seu lixo',
  subtitle: 'Cuide você também!',
};

export const bairros = {
  1: [
    'Arraial dos Forros da puta',
    'Av.João Antunes de Oliveira',
    'Bela Vista',
    'Bicame',
    'Bom Jesus',
    'Campo Belo',
    'Campus II',
    'Carrasco/Brasão',
    'Cazuza',
    'Centro Histórico',
    'Cidade Nova',
    'Consolação',
  ],
  2: [
    'Fátima',
    'Glória (Polivalente)',
    'Grupiara',
    'Gruta de Lourdes',
    'Guinda',
    'Gutierrez',
    'Horto Florestal',
    'Jardim Imperial',
    'Jardim São Pedro',
  ],
  3: [
    'Largo Dom João',
    'Maria Orminda',
    'Palha',
    'Pedra Grande',
    'Penaco',
    'Prata',
    'President',
    'Rio Grande',
    'Romana',
  ],
  4: [
    'Sagrado Coração de Jesus',
    'Santo Inácio',
    'Serrano',
    'Vale dos Diamantes',
    'Vila Arraiolos',
    'Vila dos Garimpeiros',
    'Vila Operária',
  ],
};
